[server]
  secure = false
  bind = "127.0.0.1" # what ip should the server bind to.
  port = 9090       # what port

  ssl_certificate = "cert/server.csr"
  ssl_certificate_key = "cert/server.key"

[[host]]
    # Google Example
    domain = "calendar.example.com"
    dial = "http://127.0.0.1:3000"

    cookie_passthrough = true
    cookie_encryption_key = "aaaaaaaaaaaaaaaa"

    [host.authentication]
    cookie_name = "suez_authentication_key"
    cookie_duration_days = 30

    client_id = ""
    client_secret = ""

    [host.authorization]
    cookie_name = "suez_identity_key"
    require_auth = true

    allow_all = false
    allow_list = [ "your_email@gmail.com" ]
    allow_args = [ ["permission_name", "myservice"] ]

[[host]]
    # Dropbox Example
    domain = "dropbox.example.com"
    dial = "http://127.0.0.1:3001"

    cookie_passthrough = true
    cookie_encryption_key = "aaaaaaaaaaaaaaaa"

    [host.authentication]
    cookie_name = "suez_authentication_key"
    cookie_duration_days = 30

    client_id = ""
    client_secret = ""

    init_scopes = [ "" ]

    endpoint = [
       "https://www.dropbox.com/oauth2/authorize",
       "https://www.dropbox.com/oauth2/token",
    ]

    user_info_url = "https://api.dropboxapi.com/2/users/get_current_account"
    user_info_method_post = true

    [host.authorization]
    require_auth = false
    allow_all = true
    allow_list = []

[[host]]
    domain = "*"
    [host.static]
    directory = "static/"
